---
- name: Update repositories cache and install packages
  ansible.builtin.apt:
    update_cache: true

- name: Copy Atlantis systemd service
  ansible.builtin.template:
    src: "{{ role_path }}/files/atlantis.service"
    dest: "/etc/systemd/system/atlantis.service"
    mode: "0644"
    owner: root
    group: root
  notify: Systemctl daemon-reload

- name: Copy atlantis config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/atlantis.yaml"
    dest: "/home/atlantis/.atlantis/config.yaml"
    mode: "0644"
    owner: atlantis
    group: atlantis
  notify: Restart Atlantis
