---
# System handlers

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

# System network handlers

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Restart network
  ansible.builtin.service:
    name: network
    state: restarted
  become: true

# System service handlers

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl -p
  register: sysctl_reload
  changed_when: sysctl_reload.rc == 0
  become: true

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
  become: true

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted
  become: true

- name: Restart Atlantis
  ansible.builtin.service:
    name: atlantis
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart vault
  ansible.builtin.systemd:
    name: vault
    state: restarted

- name: Check unsealed state
  ansible.builtin.uri:
    url: "{{ vault_api_addr }}/v1/sys/seal-status"
    method: GET
    body_format: json
    status_code: [200]
  register: handler_vault_status
  until: not handler_vault_status.json.sealed
  retries: 3
  delay: 2
  failed_when: false
