---

- name: CronBox
  hosts: cronbox
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
  gather_facts: true
  vars_files:
    - ../environments/cross_vars.yml
  roles:
    - cronbox
