---

- name: LegenD SharD
  hosts: legend_shard
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
  gather_facts: true
  vars_files:
    - ../environments/cross_vars.yml
  roles:
    - legend-shard
